### ISSUE TITLE
com.mongodb.MongoQueryException: CollectionScan died due to position in capped collection being deleted

### ISSUE THREAD

**Issue by HbnKing** [JinMuInfo/discussion-for-mongo#4]
Caused by: com.mongodb.MongoQueryException: Query failed with error code 136 and error message 'Executor error during find command :: caused by :: errmsg: "CollectionScan died due to position in capped collection being deleted. Last seen record id: RecordId(6852600765781915978)"' on server :27119
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:735)
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:725)
        at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:725)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:89)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:189)
        at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:143)
        at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
        at org.apache.flink.streaming.connectors.mongodb.worker.BackendOplogReader.read(BackendOplogReader.java:59)
        at org.apache.flink.streaming.connectors.mongodb.worker.Worker.read(Worker.java:178)
        at org.apache.flink.streaming.connectors.mongodb.MongoSource.run(MongoSource.java:33)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:196)

**Comment by HbnKing** [comment]
jira   [https://jira.mongodb.org/browse/SERVER-34188](https://jira.mongodb.org/browse/SERVER-34188)
