### ISSUE TITLE
com.mongodb.MongoInterruptedException: Interrupted acquiring a permit to retrieve an item from the pool 

### ISSUE THREAD

**Issue by HbnKing** [JinMuInfo/discussion-for-mongo#6]
com.mongodb.MongoInterruptedException: Interrupted acquiring a permit to retrieve an item from the pool 
        at com.mongodb.internal.connection.ConcurrentPool.acquirePermit(ConcurrentPool.java:203) ~[mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.ConcurrentPool.get(ConcurrentPool.java:140) ~[mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.ConcurrentPool.get(ConcurrentPool.java:123) ~[mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.PowerOfTwoBufferPool.getBuffer(PowerOfTwoBufferPool.java:78) ~[mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:105) ~[mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:588) ~[mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:445) ~[mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:299) ~[mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:259) ~[mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:218) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:435) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:261) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:72) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:205) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:196) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:501) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:196) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:71) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:206) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1048) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.client.internal.MongoCollectionImpl.executeInsertOne(MongoCollectionImpl.java:498) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:482) [mongo-java-driver-3.11.2.jar:na]
        at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:476) [mongo-java-driver-3.11.2.jar:na]
        at org.apache.flink.streaming.connectors.mongodb.MongodbSink.invoke(MongodbSink.java:59) [flink-connector-mongodb-0.0.1.jar:na]
        at org.apache.flink.streaming.connectors.mongodb.MongodbSink.invoke(MongodbSink.java:20) [flink-connector-mongodb-0.0.1.jar:na]
        at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56) [flink-streaming-java_2.11-1.10.0.jar:1.10.0]
        at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:173) [flink-streaming-java_2.11-1.10.0.jar:1.10.0]
        at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:151) [flink-streaming-java_2.11-1.10.0.jar:1.10.0]
        at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:128) [flink-streaming-java_2.11-1.10.0.jar:1.10.0]
        at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:69) [flink-streaming-java_2.11-1.10.0.jar:1.10.0]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:311) [flink-streaming-java_2.11-1.10.0.jar:1.10.0]
        at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:187) ~[flink-streaming-java_2.11-1.10.0.jar:1.10.0]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:487) [flink-streaming-java_2.11-1.10.0.jar:1.10.0]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:470) [flink-streaming-java_2.11-1.10.0.jar:1.10.0]
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:707) ~[flink-runtime_2.11-1.10.0.jar:1.10.0]
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:532) ~[flink-runtime_2.11-1.10.0.jar:1.10.0]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252]
Caused by: java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302) ~[na:1.8.0_252]
        at java.util.concurrent.Semaphore.acquire(Semaphore.java:312) ~[na:1.8.0_252]
        at com.mongodb.internal.connection.ConcurrentPool.acquirePermit(ConcurrentPool.java:199) ~[mongo-java-driver-3.11.2.jar:na]
        ... 41 common frames omitted

**Comment by HbnKing** [comment]
jira  [https://jira.mongodb.org/browse/JAVA-2091](https://jira.mongodb.org/browse/JAVA-2091)
