### ISSUE TITLE
 com.mongodb.MongoInternalException: The responseTo (304592644) in the response does not match the requestId (304592647) in the request

### ISSUE THREAD

**Issue by HbnKing** [JinMuInfo/discussion-for-mongo#7]
com.mongodb.MongoInternalException: The responseTo (304592644) in the response does not match the requestId (304592647) in the request
        at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:65)
        at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:43)
        at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:409)
        at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:305)
        at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
        at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:83)
        at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:38)
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:180)
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:124)
        at java.lang.Thread.run(Thread.java:745)

**Comment by HbnKing** [comment]
MongoDB. 内部异常  表象为 session id  不一致。   
即使版本兼容也有发生
